"use client";

import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { 
  Play, 
  CheckCircle2, 
  Terminal, 
  Activity, 
  Zap, 
  Sparkles,
  Server,
  Globe2,
  Cpu
} from "lucide-react";

interface InteractiveDemoModalProps {
  isOpen: boolean;
  onClose: () => void;
  mode: "demo" | "create";
}

export function InteractiveDemoModal({
  isOpen,
  onClose,
  mode,
}: InteractiveDemoModalProps) {
  // Demo state
  const [activeTab, setActiveTab] = useState<"edge" | "inference" | "workflow">("edge");
  const [latencies, setLatencies] = useState([
    { region: "US East (N. Virginia)", ping: 14, status: "Optimal" },
    { region: "EU Central (Frankfurt)", ping: 18, status: "Optimal" },
    { region: "AP East (Tokyo)", ping: 26, status: "Optimal" },
    { region: "AP South (Singapore)", ping: 22, status: "Optimal" },
    { region: "SA East (São Paulo)", ping: 35, status: "Optimal" },
  ]);

  // AI Inference demo state
  const [prompt, setPrompt] = useState("Generate an edge-optimized serverless route");
  const [isGenerating, setIsGenerating] = useState(false);
  const [output, setOutput] = useState("");

  // Create Workspace state
  const [workspaceName, setWorkspaceName] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Periodically refresh ping values slightly for live feel
  useEffect(() => {
    if (!isOpen || mode !== "demo") return;
    const interval = setInterval(() => {
      setLatencies((prev) =>
        prev.map((item) => ({
          ...item,
          ping: Math.max(10, item.ping + Math.floor(Math.random() * 5 - 2)),
        }))
      );
    }, 2000);
    return () => clearInterval(interval);
  }, [isOpen, mode]);

  const handleRunInference = () => {
    setIsGenerating(true);
    setOutput("");
    const text = `// Generated by Quolix AI Engine\nexport default async function handler(req: Request) {\n  const ip = req.headers.get("x-quolix-edge-ip");\n  return Response.json({\n    status: "live",\n    latency: "1.2ms",\n    engine: "Quolytech Kernel v3.4"\n  });\n}`;
    let index = 0;
    const timer = setInterval(() => {
      if (index < text.length) {
        setOutput((prev) => prev + text.charAt(index));
        index++;
      } else {
        clearInterval(timer);
        setIsGenerating(false);
        toast.success("Generation completed at 240 tokens/sec");
      }
    }, 15);
  };

  const handleCreateWorkspace = (e: React.FormEvent) => {
    e.preventDefault();
    if (!workspaceName.trim()) {
      toast.error("Please enter a workspace name");
      return;
    }
    setIsSubmitting(true);
    setTimeout(() => {
      setIsSubmitting(false);
      onClose();
      toast.success(`Workspace "${workspaceName}" initialized!`, {
        description: `Live at https://${workspaceName.toLowerCase().replace(/\s+/g, "-")}.quolix.sh • Made by Quolytech`,
      });
      setWorkspaceName("");
    }, 1000);
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-2xl bg-background border border-foreground/15 p-0 overflow-hidden text-foreground">
        {mode === "demo" ? (
          <div>
            {/* Header */}
            <div className="p-6 border-b border-foreground/10 bg-foreground/[0.02]">
              <div className="flex items-center justify-between mb-2">
                <span className="font-mono text-xs uppercase tracking-widest text-muted-foreground">
                  Interactive Platform Tour
                </span>
                <span className="px-2.5 py-0.5 rounded-full border border-foreground/15 text-[10px] font-mono bg-foreground/5 text-foreground/80">
                  Made by Quolytech
                </span>
              </div>
              <DialogTitle className="text-2xl font-display">Quolix Runtime Engine</DialogTitle>
              <DialogDescription className="text-muted-foreground text-sm">
                Explore real-time global edge orchestration and AI inference latency.
              </DialogDescription>

              {/* Tabs */}
              <div className="flex items-center gap-2 mt-4">
                <button
                  type="button"
                  onClick={() => setActiveTab("edge")}
                  className={`px-3 py-1.5 rounded-full text-xs font-mono transition-colors flex items-center gap-1.5 ${
                    activeTab === "edge"
                      ? "bg-foreground text-background"
                      : "bg-foreground/5 text-foreground/70 hover:text-foreground"
                  }`}
                >
                  <Globe2 className="w-3.5 h-3.5" />
                  Edge Latency
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("inference")}
                  className={`px-3 py-1.5 rounded-full text-xs font-mono transition-colors flex items-center gap-1.5 ${
                    activeTab === "inference"
                      ? "bg-foreground text-background"
                      : "bg-foreground/5 text-foreground/70 hover:text-foreground"
                  }`}
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  AI Inference
                </button>
                <button
                  type="button"
                  onClick={() => setActiveTab("workflow")}
                  className={`px-3 py-1.5 rounded-full text-xs font-mono transition-colors flex items-center gap-1.5 ${
                    activeTab === "workflow"
                      ? "bg-foreground text-background"
                      : "bg-foreground/5 text-foreground/70 hover:text-foreground"
                  }`}
                >
                  <Server className="w-3.5 h-3.5" />
                  Architecture
                </button>
              </div>
            </div>

            {/* Content Area */}
            <div className="p-6">
              {activeTab === "edge" && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between text-xs font-mono text-muted-foreground pb-2 border-b border-foreground/10">
                    <span>Target Region</span>
                    <span>Live Ping & Status</span>
                  </div>
                  {latencies.map((loc) => (
                    <div
                      key={loc.region}
                      className="flex items-center justify-between p-3 rounded-lg border border-foreground/10 bg-foreground/[0.01] hover:bg-foreground/[0.03] transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                        <span className="text-sm font-medium">{loc.region}</span>
                      </div>
                      <div className="flex items-center gap-3 font-mono text-xs">
                        <span className="text-foreground">{loc.ping}ms</span>
                        <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                          {loc.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {activeTab === "inference" && (
                <div className="space-y-4">
                  <div className="flex gap-2">
                    <Input
                      value={prompt}
                      onChange={(e) => setPrompt(e.target.value)}
                      placeholder="Enter instruction for the Quolix AI compiler..."
                      className="text-sm font-mono"
                    />
                    <Button
                      onClick={handleRunInference}
                      disabled={isGenerating}
                      className="bg-foreground text-background shrink-0 rounded-lg text-xs font-mono"
                    >
                      <Zap className="w-3.5 h-3.5 mr-1" />
                      {isGenerating ? "Compiling..." : "Generate"}
                    </Button>
                  </div>

                  <div className="p-4 rounded-lg bg-foreground/[0.03] border border-foreground/10 font-mono text-xs min-h-[160px]">
                    <pre className="text-foreground/90 whitespace-pre-wrap leading-relaxed">
                      {output || "// Click Generate to execute live code synthesis..."}
                    </pre>
                  </div>
                </div>
              )}

              {activeTab === "workflow" && (
                <div className="space-y-4">
                  <div className="grid grid-cols-3 gap-3 text-center">
                    <div className="p-4 rounded-lg border border-foreground/10 bg-foreground/[0.01]">
                      <Terminal className="w-5 h-5 mx-auto mb-2 text-foreground/70" />
                      <div className="text-xs font-mono font-medium">1. Code & Push</div>
                      <div className="text-[11px] text-muted-foreground mt-1">Git commit hook or SDK CLI</div>
                    </div>
                    <div className="p-4 rounded-lg border border-foreground/10 bg-foreground/[0.01]">
                      <Cpu className="w-5 h-5 mx-auto mb-2 text-foreground/70" />
                      <div className="text-xs font-mono font-medium">2. AI Optimization</div>
                      <div className="text-[11px] text-muted-foreground mt-1">Tree shaking & Edge compile</div>
                    </div>
                    <div className="p-4 rounded-lg border border-foreground/10 bg-foreground/[0.01]">
                      <Globe2 className="w-5 h-5 mx-auto mb-2 text-foreground/70" />
                      <div className="text-xs font-mono font-medium">3. Global Delivery</div>
                      <div className="text-[11px] text-muted-foreground mt-1">Instant sync to 200+ PoPs</div>
                    </div>
                  </div>
                  <div className="p-4 rounded-lg bg-foreground/[0.02] border border-foreground/10 text-xs text-muted-foreground flex items-center justify-between">
                    <span>Engineered with high concurrency by Quolytech</span>
                    <span className="font-mono text-foreground font-semibold">99.999% SLA</span>
                  </div>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="p-4 border-t border-foreground/10 bg-foreground/[0.01] flex items-center justify-between">
              <span className="text-xs font-mono text-muted-foreground">
                Quolix v2.4 • Edge Kernel
              </span>
              <Button
                size="sm"
                onClick={onClose}
                className="bg-foreground text-background rounded-full px-5 text-xs"
              >
                Close preview
              </Button>
            </div>
          </div>
        ) : (
          /* Create Workspace Modal */
          <div className="p-8">
            <div className="flex items-center justify-between mb-4">
              <span className="font-mono text-xs uppercase tracking-widest text-muted-foreground">
                Quick Setup
              </span>
              <span className="text-[11px] font-mono text-muted-foreground">
                Made by Quolytech
              </span>
            </div>
            <DialogTitle className="text-3xl font-display tracking-tight mb-2">
              Start building with Quolix
            </DialogTitle>
            <DialogDescription className="text-muted-foreground mb-6">
              Spin up your isolated high-speed cloud workspace in seconds.
            </DialogDescription>

            <form onSubmit={handleCreateWorkspace} className="space-y-5">
              <div>
                <label className="block text-xs font-mono text-muted-foreground mb-2">
                  Workspace Name
                </label>
                <Input
                  value={workspaceName}
                  onChange={(e) => setWorkspaceName(e.target.value)}
                  placeholder="e.g. acme-corp"
                  className="font-mono text-sm h-11"
                  required
                />
                <p className="text-[11px] font-mono text-muted-foreground mt-1.5">
                  Your workspace will be instantly accessible at https://{workspaceName ? workspaceName.toLowerCase().replace(/\s+/g, "-") : "workspace"}.quolix.sh
                </p>
              </div>

              <div className="pt-2 flex items-center justify-end gap-3">
                <Button
                  type="button"
                  variant="outline"
                  onClick={onClose}
                  className="rounded-full px-5 text-sm"
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-foreground text-background hover:bg-foreground/90 rounded-full px-7 text-sm font-medium"
                >
                  {isSubmitting ? "Provisioning..." : "Launch workspace"}
                </Button>
              </div>
            </form>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
